### ISSUE TITLE
ARM64EC vs Emulation

### ISSUE THREAD

**Issue by lexcyn** [arminask/windows-arm-apps#112]
Now that I have my Surface Laptop, I've been going through some of the apps that are listed here. I think there is some confusion on which apps are ARM64EC or just running in emulation.

You can check task manager to see the architecture the process is running in:
- Native = will show up as "arm64"
- ARM64EC = shows up in as "arm64 (x64 Compatible)"
- Emulation = shows up as either "x64" or "x86"

@arminask I wonder if it's worth modifying the readme to include this information - [Edit: Never mind about CapCut, but I do have a list of some other apps that are running in emulation and not ARM64EC/arm64 that were mis-identified]

**Comment by talynone** [comment]
Which apps are not native? I've yet to find a mistake.

**Comment by lexcyn** [comment]
> Which apps are not native? I've yet to find a mistake. Sometimes the ARM64 download link is harder to find on the page, but it's there.

Configuration Manager for example - there is no native or even ARM64EC version of this, it's entirely emulated. There are a few others that are dubious adds, like Twitter, Instagram, etc as they are just web apps (you can tell when the architecture is set as "neutral".

**Comment by arminask** [comment]
I do think it's maybe worth including the clarification in About/Resources section of the page regarding the ARM64/EC, emulation.

**Comment by J-S0117** [comment]
> > Which apps are not native? I've yet to find a mistake. Sometimes the ARM64 download link is harder to find on the page, but it's there.
> 
> Configuration Manager for example - there is no native or even ARM64EC version of this, it's entirely emulated. There are a few others that are dubious adds, like Twitter, Instagram, etc as they are just web apps (you can tell when the architecture is set as "neutral").

I came on this website for the exact same reason. I saw that Configuration Manager was on here, but after some investigation found that it is emulated.

**Comment by lexcyn** [comment]
> > > Which apps are not native? I've yet to find a mistake. Sometimes the ARM64 download link is harder to find on the page, but it's there.
> > 
> > 
> > Configuration Manager for example - there is no native or even ARM64EC version of this, it's entirely emulated. There are a few others that are dubious adds, like Twitter, Instagram, etc as they are just web apps (you can tell when the architecture is set as "neutral").
> 
> I came on this website for the exact same reason. I saw that Configuration Manager was on here, but after some investigation found that it is emulated.

Removed in #115
