### ISSUE TITLE
Add Remote Desktop Manager by Devolutions

### ISSUE THREAD

**Issue by worldsdream** [arminask/windows-arm-apps#116]
[Remote Desktop Manager ](https://devolutions.net/remote-desktop-manager/) added ARM64 support since:

Version 2022.3.14.0 (November 1, 2022)
https://devolutions.net/remote-desktop-manager/release-notes/

If you can add it to the homepage with the URL: https://devolutions.net/remote-desktop-manager/

Thanks!

**Comment by talynone** [comment]
Created pull request for it, should be added soon

https://github.com/arminask/windows-arm-apps/pull/121

**Comment by arminask** [comment]
Added with merged PR [#121](https://github.com/arminask/windows-arm-apps/pull/121)
