### ISSUE TITLE
Add Android Studio

### ISSUE THREAD

**Issue by NikSavchenk0** [arminask/windows-arm-apps#120]
![studio_splash_arm64@2x](https://github.com/user-attachments/assets/74b7c579-0da2-434f-a78d-79d5b51aa398)

**Comment by lexcyn** [comment]
@NikSavchenk0 incorrect, this was a release targeting Apple Silicon arm64 NOT Windows. Currently there is no native Windows ARM64 version, as per their official system requirements: https://developer.android.com/studio/install
