### ISSUE TITLE
Telegram ARM64

### ISSUE THREAD

**Issue by lexcyn** [arminask/windows-arm-apps#130]
Hi all - looks like you can now compile an arm64 native version of Telegram as all dependencies can be compiled natively. You can follow the regular build guide except:

Follow the regular build guide except the following changes:

- Run the ARM64 Native Tools Command Prompt
- Use Python 3.11 (ARM native build)
- Edit the `tdesktop\cmake\variables.cmake` file and adjust the following:
-     `if (CMAKE_SYSTEM_PROCESSOR MATCHES "arm")` change to `if (CMAKE_SYSTEM_PROCESSOR MATCHES "ARM*")`
- Change the arch in the build step to: `configure.bat arm qt6 -D TDESKTOP_API_ID=YOUR_API_ID -D TDESKTOP_API_HASH=YOUR_API_HASH`
- Note that I had to specify `qt6` in order to get the build to work but you may not need to

<img width="177" alt="image" src="https://github.com/user-attachments/assets/7ccef2fa-11c5-4e93-85e0-7decfed27567">

Not sure if this counts to be added @arminask ? :)

**Comment by arminask** [comment]
Wow this is awesome, finally!

**Comment by arminask** [comment]
And yes, I think this can definitely be added. Afaik there are no pre-compiled official builds?

**Comment by lexcyn** [comment]
> And yes, I think this can definitely be added. Afaik there are no pre-compiled official builds?

Correct no official version yet
