### ISSUE TITLE
Webex erroneously listed as ARM64 native

### ISSUE THREAD

**Issue by irvelervel** [arminask/windows-arm-apps#133]
Hi, I think there is a mistake in the "Social" list, Cirsco does not seem to provide ARM64 binaries for their Webex app.
Their download page just allows to download the x86 app for Windows, and downloading it from the Microsoft Store indeed installs the same binaries.
The app works mostly fine, but just through emulation. I have a couple of weird bugs on a SP11 device (a popup error at the startup and virtual backgrounds do not get saved).

I'd be happy to be proved wrong!
Cheers

<img width="173" alt="Screenshot 2024-09-07 183930" src="https://github.com/user-attachments/assets/aec23c25-084b-4bb5-8d44-1013c31387d3">

**Comment by arminask** [comment]
Hey, thanks for the observation. It would need to be removed then.

**Comment by talynone** [comment]
@arminask In pull request https://github.com/arminask/windows-arm-apps/pull/135

**Comment by arminask** [comment]
Merged in @talynone's #135 PR.
