### ISSUE TITLE
Is it not possible to make an Nvidia GPU driver for Windows on ARM processors ?

### ISSUE THREAD

**Issue by Tufan0066** [arminask/windows-arm-apps#138]
Is it not possible to make an Nvidia GPU driver for Windows on ARM processors ?

Ampere Altra and AmpereOne ARM processors already support Windows on ARM.

Nvidia GPU drivers are already available for Linux on ARM. We just need Nvidia GPU drivers for Windows on ARM. Can't we modify Windows x86-64 Nvidia GPU drivers to work for Windows on ARM ? 

https://www.youtube.com/watch?v=ydGdHjIncbk&t=54s

**Comment by arminask** [comment]
Uhh well, I think your question is beyond this project's scope. I'm not an expert, but if Windows Nvidia drivers are open source, then maybe theoretically you can?

**Comment by talynone** [comment]
The source code for the windows driver is closed source so there's no way to build it. Even on Linux the Nvidia driver is considered terrible and most recommend using an AMD card for best results on Linux. 

There's also no incentive for Nvidia to put in the resources to build an ARM driver. Maybe if they came out with their own ARM Windows processor.

**Comment by driver1998** [comment]
We now know the RTX Spark is coming, and NVIDIA released a preview version of their ARM64 Windows GPU drivers.
https://forums.developer.nvidia.com/t/rtx-spark-developer-preview/377106

Although it is technically for RTX Spark only and therefore its INF has all the PCIe dGPU HWIDs removed, it can still be used with a normal dGPU. In Device Manager, select "NVIDIA Desktop Device" to force install this driver on your GPU.

There are people who get it working with RTX 2080Ti and RTX 4060 (on the Orion O6 board). It is believed that anything Turing and up will work.

Some videos:
https://www.bilibili.com/video/BV1qVK26rEj7
https://www.bilibili.com/video/BV1dRKW65EYn/
