### ISSUE TITLE
Adding printer driver/software?

### ISSUE THREAD

**Issue by lexcyn** [arminask/windows-arm-apps#141]
Hey @arminask how do you feel about adding printer software/drivers? Some of the larger manufacturers have ARM64 native driver packs that could technically be considered software, but I know there are quite a few people looking for printer drivers so this might help. Sub heading could include info about how to find which models are supported, as they are usually listed in the software documentation PDF.

I could create a new section for Printers or Drivers if you're good with it!

**Comment by talynone** [comment]
I think that would be a great idea

**Comment by lexcyn** [comment]
Thanks all! I will work on getting these added over the weekend!
