### ISSUE TITLE
Add NordVPN

### ISSUE THREAD

**Issue by worldsdream** [arminask/windows-arm-apps#151]
Can you please add NordVPN to the list:

https://nordvpn.com/blog/windows-arm-release/

Support added from v7.29

**Comment by lexcyn** [comment]
This was added in #150 

> Can you please add NordVPN to the list:
> 
> https://nordvpn.com/blog/windows-arm-release/
> 
> Support added from v7.29

**Comment by talynone** [comment]
@arminask Looks like last merge failed.
