### ISSUE TITLE
Anyone tried Cyberlink softwares on Windows on ARM processor ?

### ISSUE THREAD

**Issue by Tufan0066** [arminask/windows-arm-apps#171]
Cyberlink PowerDirector 2025/365 (version 22.6 or above), PhotoDirector 2025/365 (version 15.7 or above), Screen Recorder 4 SE support link for Windows on ARM processor - https://www.cyberlink.com/support-center/faq/content?id=29176

It is mentioned here that Qualcomm (Windows 11 x64 ARM only), Snapdragon® 8cx Gen 3, Snapdragon® X Elite are supported.

CyberLink PowerDirector 2025/365 system requirements - https://www.cyberlink.com/support-center/faq/content?id=29376

CyberLink PhotoDirector 2025/365 system requirements - https://www.cyberlink.com/support-center/faq/content?id=29311

Screen Recorder 4 SE supported system requirements - https://www.cyberlink.com/support-center/faq/content?id=29176

Does anyone use CyberLink softwares and can confirm this ?

**Comment by talynone** [comment]
I installed PowerDirector trial in a Windows ARM Sandbox, it installs/runs fine but it's not ARM native. It shows the process running as a x64 app, so it's running under emulation.

**Comment by Tufan0066** [comment]
> I installed PowerDirector trial in a Windows ARM Sandbox, it installs/runs fine but it's not ARM native. It shows the process running as a x64 app, so it's running under emulation.

PowerDirector 2025/365 (version 22.6 or above), right ?

What about PhotoDirector 2025/365 (version 15.7 or above) and Screen Recorder 4 SE ?

**Comment by talynone** [comment]
> > I installed PowerDirector trial in a Windows ARM Sandbox, it installs/runs fine but it's not ARM native. It shows the process running as a x64 app, so it's running under emulation.
> 
> PowerDirector 2025/365 (version 22.6 or above), right ?
> 
> What about PhotoDirector 2025/365 (version 15.7 or above) and Screen Recorder 4 SE ?

Yes the trial downloads and installs the latest version, you can try it yourself for free. They're all x64 apps.
