### ISSUE TITLE
Add "Globs" to games ( I tried it for 3 hours now and am too stupid :c )

### ISSUE THREAD

**Issue by Otozinclus** [arminask/windows-arm-apps#183]
Globs is a new Indie Puzzle game, made with Godot 4.3. The devs have published the source code with a guide on how to export it (Very easy!). Godot added official Windows Arm support with Version 4.3, therefore the Game can get compiled for Windows Arm natively without any issues. Considering all other native Windows Arm games on the list are very old, I think it is a very nice addition to the list

Here is the GitHub link: https://github.com/ARKANYOTA/globs

Though, I don't know how this works in terms of licencing

**Comment by talynone** [comment]
We only post links to binaries. If someone wants to build it for ARM64 and host the binary then we can add it.

**Comment by Otozinclus** [comment]
Okay thanks. That sadly won't happen, because redistribution by third parties is against the licence, but thanks for responding
