### ISSUE TITLE
Missing PWA (progressive web app) icons

### ISSUE THREAD

**Issue by lexcyn** [arminask/windows-arm-apps#65]
I noticed that there is a missing icon for the PWA - not sure if this is required or not - but might be worthwhile to add:

![image](https://github.com/arminask/windows-arm-apps/assets/23508813/021737d8-3d04-49f4-bbed-53c5e422e285)

/assets/icons/pwa-192x192.png is the file referenced in the error.

**Comment by arminask** [comment]
It's a Homer dashboard logo: https://github.com/bastienwirtz/homer/blob/main/public/assets/icons/pwa-192x192.png
Maybe worth adding, though then we should replace the homer logo to ours (if this project even has a logo), it's just a microsoft store icon :?

**Comment by lexcyn** [comment]
Hmm, yes if we do it we should get our own logo, I think that would be pretty cool to do!

**Comment by lexcyn** [comment]
![1](https://github.com/arminask/windows-arm-apps/assets/23508813/9186b355-0bab-4e1e-8463-25b81de1d459)

I made this one in Microsoft Designer...  haha :)
