### ISSUE TITLE
Leonardo, a painting software

### ISSUE THREAD

**Issue by Elaman0117** [arminask/windows-arm-apps#7]
```
- name: "Leonardo"
        logo: "assets/tools/leonardo.png"
        url: "https://www.getleonardo.com/download/"
        target: "_blank"
```

**Comment by Elaman0117** [comment]
![apps.64001.13510798887527153.5be34a24-8886-4d9f-9bd5-72f9bfca0316.png](https://github.com/arminask/windows-arm-apps/assets/86803919/b28d3094-3457-43bd-ae88-075a1f4baeff)

**Comment by ArminiusTux** [comment]
Dear @Elaman0117 , the application has been added - thanks for nominating it.
