### ISSUE TITLE
Teamviewer

### ISSUE THREAD

**Issue by SubSolar0** [arminask/windows-arm-apps#76]
Are you sure Teamviewer has an ARM version for Windows? I see only a Linux version on their website and when I googled about it I just found people asking when they're making a Windows ARM64 version

**Comment by lexcyn** [comment]
I'll contact our enterprise support and find out. I will have my Surface laptop hopefully this week and will be able to confirm if the MSI contains the ARM version similar to other products.

**Comment by lexcyn** [comment]
Removed in latest commit pending support request: https://github.com/arminask/windows-arm-apps/pull/79

**Comment by arminask** [comment]
Changes merged
