### ISSUE TITLE
Remove Unigram?

### ISSUE THREAD

**Issue by dongle-the-gadget** [arminask/windows-arm-apps#78]
Unigram as of right now only runs emulated on ARM64, and [the developer has said he will not develop an ARM64 version](https://github.com/UnigramDev/Unigram/issues/3010#issuecomment-2141713165).

**Comment by lexcyn** [comment]
Removed in: https://github.com/arminask/windows-arm-apps/pull/79

**Comment by arminask** [comment]
Merged

**Comment by dongle-the-gadget** [comment]
Resolved in #79
