### ISSUE TITLE
PPSSPP

### ISSUE THREAD

**Issue by Elaman0117** [arminask/windows-arm-apps#8]
```
- name: "PPSSPP"
        logo: "assets/tools/ppsspp.png"
        url: "https://www.ppsspp.org/download"
        target: "_blank"
```
![ppsspp-icon.png](https://github.com/arminask/windows-arm-apps/assets/86803919/91edc483-a4b8-4bc2-a29f-40ad907f43d0)

**Comment by ArminiusTux** [comment]
Also added this PSP emulator. 
You are more than welcome to fork this project and place the additions into the `assets/config.yml`
If you need an icon editor, I can recommend [IcoFX](https://icofx.ro/).

In any case keep the native apps coming!😉
