### ISSUE TITLE
search hyperlinks aren't working

### ISSUE THREAD

**Issue by ArminiusTux** [arminask/windows-arm-apps#81]
Not a big deal, 

but if you really want to recommend a native Windows on ARM app in a fast & simple way,

you just use the search function on

[https://armrepo.ver.lt/](https://armrepo.ver.lt/)

and copy the [search URL](https://armrepo.ver.lt/?search=ARM32) from the address bar.

Sadly this link will not redo the search upon opening - in fact you have to use the search box again and retype it.

Since [this search operation is working](https://homer-demo.netlify.app/?search=selfhosted) on [homer](https://github.com/bastienwirtz/homer) by @bastienwirtz , we might need to update our "bone structure". 

I stumbled upon this micro-issue a while ago, but [only recently made use of the search links](https://github.com/ArminiusTux/lusrmgr/releases).

**Comment by arminask** [comment]
You're right, current Homer page that this website uses is very outdated. I will work on this when I have some time. I think other things also need some changes, like the project readme update, etc.

**Comment by arminask** [comment]
Fixed. Created a manually triggered workflow that updates Homer dashboard base files and then creates a pull request.
Now updating project's "bone structure" won't be so difficult :)

Updated Homer to the latest version, search hyperlinks are now working.

**Comment by ArminiusTux** [comment]
Thanks for the quick fix and kudos for that nifty semi-automatic update mechanism. 😉
